// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SignalGenEsp32

#ifndef _UI_COMP_BUTTONLIST_H
#define _UI_COMP_BUTTONLIST_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ButtonList
#define UI_COMP_BUTTONLIST_BUTTONLIST 0
#define UI_COMP_BUTTONLIST_LABEL4 1
#define _UI_COMP_BUTTONLIST_NUM 2
lv_obj_t * ui_ButtonList_create(lv_obj_t * comp_parent);
void ui_event_comp_ButtonList_ButtonList(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
