// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SignalGenEsp32

#include "ui.h"


void ui_event_comp_ButtonList_ButtonList(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_ButtonList = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Main_screen_init);
    }
}

// COMPONENT ButtonList

lv_obj_t * ui_ButtonList_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ButtonList;
    cui_ButtonList = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_ButtonList, lv_pct(60));
    lv_obj_set_height(cui_ButtonList, lv_pct(20));
    lv_obj_set_x(cui_ButtonList, -80);
    lv_obj_set_y(cui_ButtonList, 98);
    lv_obj_set_align(cui_ButtonList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_ButtonList, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_ButtonList, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_add_flag(cui_ButtonList, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_ButtonList, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label4;
    cui_Label4 = lv_label_create(cui_ButtonList);
    lv_obj_set_width(cui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label4, -183);
    lv_obj_set_y(cui_Label4, -1);
    lv_obj_set_align(cui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label4, "Data");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTONLIST_NUM);
    children[UI_COMP_BUTTONLIST_BUTTONLIST] = cui_ButtonList;
    children[UI_COMP_BUTTONLIST_LABEL4] = cui_Label4;
    lv_obj_add_event_cb(cui_ButtonList, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ButtonList, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_ButtonList, ui_event_comp_ButtonList_ButtonList, LV_EVENT_ALL, children);
    ui_comp_ButtonList_create_hook(cui_ButtonList);
    return cui_ButtonList;
}

