// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SignalGenEsp32

#ifndef _SIGNALGENESP32_UI_H
#define _SIGNALGENESP32_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Logo
void ui_Logo_screen_init(void);
void ui_event_Logo(lv_event_t * e);
extern lv_obj_t * ui_Logo;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

// SCREEN: ui_Logo0
void ui_Logo0_screen_init(void);
void ui_event_Logo0(lv_event_t * e);
extern lv_obj_t * ui_Logo0;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

// SCREEN: ui_ErrorSD
void ui_ErrorSD_screen_init(void);
extern lv_obj_t * ui_ErrorSD;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_Explorador
void ui_Explorador_screen_init(void);
extern lv_obj_t * ui_Explorador;
extern lv_obj_t * ui_Container1;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Roller3;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container7;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label10;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label11;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
// CUSTOM VARIABLES

// SCREEN: ui_Loading
void ui_Loading_screen_init(void);
extern lv_obj_t * ui_Loading;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_Label13;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_423428936);    // assets/WhatsApp Image 2024-09-08 at 20.31.55_287d4613.png
LV_IMG_DECLARE(ui_img_1162731896);    // assets/simbolo-de-doble-flecha-derecha-de-avance-rapido (2).png
LV_IMG_DECLARE(ui_img_1081796697);    // assets/simbolo-de-doble-flecha-derecha-de-avance-rapido (1).png
LV_IMG_DECLARE(ui_img_1760988675);    // assets/actualizar-flecha.png
LV_IMG_DECLARE(ui_img_1486996648);    // assets/up-arrow.png
LV_IMG_DECLARE(ui_img_1407471917);    // assets/down-arrow.png
LV_IMG_DECLARE(ui_img_1718651389);    // assets/play-and-pause-button.png
LV_IMG_DECLARE(ui_img_restart_png);    // assets/restart.png
LV_IMG_DECLARE(ui_img_return_png);    // assets/return.png
LV_IMG_DECLARE(ui_img_config_png);    // assets/config.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
