// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SignalGenEsp32

#ifndef _SIGNALGENESP32_UI_H
#define _SIGNALGENESP32_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_Logo
void ui_Logo_screen_init(void);
void ui_event_Logo(lv_event_t * e);
extern lv_obj_t * ui_Logo;
extern lv_obj_t * ui_Label7;
// SCREEN: ui_Explorador
void ui_Explorador_screen_init(void);
extern lv_obj_t * ui_Explorador;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Roller3;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container7;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_Chart4;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Button7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
// SCREEN: ui_Config
void ui_Config_screen_init(void);
extern lv_obj_t * ui_Config;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1162731896);    // assets/simbolo-de-doble-flecha-derecha-de-avance-rapido (2).png
LV_IMG_DECLARE(ui_img_1081796697);    // assets/simbolo-de-doble-flecha-derecha-de-avance-rapido (1).png
LV_IMG_DECLARE(ui_img_1760988675);    // assets/actualizar-flecha.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
