// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SignalGenEsp32

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void rollerUp(lv_event_t * e);
void rollerDown(lv_event_t * e);
void openTarget(lv_event_t * e);
void SignalStartStop(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
