// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SignalGenEsp32

#include "ui.h"

void exitLogo(lv_event_t * e)
{
	// Your code here
}

void backDirectory(lv_event_t * e)
{
	// Your code here
}

void nextDirectory(lv_event_t * e)
{
	// Your code here
}

void refreshRollerButton(lv_event_t * e)
{
	// Your code here
}

void rollerUp(lv_event_t * e)
{
	// Your code here
}

void rollerDown(lv_event_t * e)
{
	// Your code here
}

void openTarget(lv_event_t * e)
{
	// Your code here
}

void SignalStartStop(lv_event_t * e)
{
	// Your code here
}

void resetSignal(lv_event_t * e)
{
	// Your code here
}
