// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SignalGenEsp32

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void exitLogo(lv_event_t * e);
void backDirectory(lv_event_t * e);
void nextDirectory(lv_event_t * e);
void refreshRollerButton(lv_event_t * e);
void rollerUp(lv_event_t * e);
void rollerDown(lv_event_t * e);
void openTarget(lv_event_t * e);
void SignalStartStop(lv_event_t * e);
void resetSignal(lv_event_t * e);
void downFrecuency(lv_event_t * e);
void upFrecuency(lv_event_t * e);
void resetSignalComplete(lv_event_t * e);
void AnimtoExplorer(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
