// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SignalGenEsp32

#include "ui.h"

void ui_Plot_screen_init(void)
{
    ui_Plot = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Plot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Plot, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Plot, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_Container4 = lv_obj_create(ui_Plot);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(100));
    lv_obj_set_height(ui_Container4, lv_pct(80));
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Container4, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW |
                    LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Chart1 = lv_chart_create(ui_Container4);
    lv_obj_set_width(ui_Chart1, lv_pct(80));
    lv_obj_set_height(ui_Chart1, lv_pct(80));
    lv_obj_set_x(ui_Chart1, -21);
    lv_obj_set_y(ui_Chart1, -75);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart1, 100);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 5);
    lv_chart_set_div_line_count(ui_Chart1, 5, 7);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 5, 5, 10, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);



    ui_Container8 = lv_obj_create(ui_Plot);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, lv_pct(80));
    lv_obj_set_height(ui_Container8, lv_pct(20));
    lv_obj_set_x(ui_Container8, 2);
    lv_obj_set_y(ui_Container8, -19);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button15 = lv_btn_create(ui_Container8);
    lv_obj_set_width(ui_Button15, lv_pct(100));
    lv_obj_set_height(ui_Button15, lv_pct(70));
    lv_obj_set_x(ui_Button15, -8);
    lv_obj_set_y(ui_Button15, -37);
    lv_obj_set_align(ui_Button15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0x2F71EC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button15, &ui_img_1162731896, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);

}
